import type { Product } from './types';

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Organic Apples',
    price: 3.99,
    description: 'Crisp and juicy organic apples, perfect for snacking or baking.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'apples fruit',
    category: 'fruits',
    inStock: true,
    discount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Whole Wheat Bread',
    price: 4.49,
    description: 'Freshly baked whole wheat bread, rich in fiber.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'bread bakery',
    category: 'bakery',
    inStock: true,
    discount: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Free-Range Eggs',
    price: 5.99,
    description: 'A dozen large free-range eggs, great for breakfast.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'eggs dairy',
    category: 'dairy',
    inStock: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Organic Spinach',
    price: 2.99,
    description: 'A bag of fresh organic spinach, packed with nutrients.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'spinach vegetables',
    category: 'vegetables',
    inStock: true,
    discount: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Almond Milk',
    price: 3.79,
    description: 'Unsweetened almond milk, a great dairy-free alternative.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'almond milk',
    category: 'dairy',
    inStock: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Chicken Breast',
    price: 9.99,
    description: 'Boneless, skinless chicken breast, lean and versatile.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'chicken meat',
    category: 'meat',
    inStock: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Brown Rice',
    price: 2.49,
    description: 'Long-grain brown rice, a healthy whole grain option.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'rice grains',
    category: 'grains',
    inStock: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Greek Yogurt',
    price: 4.99,
    description: 'Creamy Greek yogurt, high in protein and probiotics.',
    image: 'https://placehold.co/300x200.png',
    dataAiHint: 'yogurt dairy',
    category: 'dairy',
    inStock: true,
    discount: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];
